### PR TITLE
Update Windows install notes

### PR DESCRIPTION
**Pull request by attie**
There are a few steps that need revising on the Windows install.

I also noticed that I needed to apply the following fix to all files that use FFTS. I'm not sure how to best document this, and I imagine making this change will affect / break Linux...?

```patch
-#include <ffts.h>
+#include <ffts/ffts.h>
```

### CODE REVIEW

**Comment by nshcat** [comment]
I will look into modifying how cmake handles the ffts include path on windows, so the source files don't need to be changed.

**Comment by attie** [comment]
@nshcat - thanks!

In IRC, @azonenberg suggested comparing the documented steps vs. CI scripts... I don't have time to do this now unfortunately

**Comment by azonenberg** [comment]
@nshcat The GitHub Actions CI build currently works without any patching of code. it's possible the documentation disagrees with the CI build process.

**Comment by azonenberg** [comment]
Merging and closing this PR as the requested doc changes are all good.

@nshcat The FFTS include path issues are unrelated, file a separate ticket against either scopehal-apps (if bug is on the build system/code side) or scopehal-docs (if build instructions are wrong) once you've investigated.

**Pull request merged**
